name: bigdataspark-lab2

services:
  postgres:
    image: postgres:16-alpine
    container_name: bigdataspark-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - "./src_data:/mock_data:ro"
    networks:
      - lab-network

  clickhouse:
    image: clickhouse/clickhouse-server:24.8-alpine
    container_name: bigdataspark-clickhouse
    environment:
      CLICKHOUSE_DB: lab2
      ADMIN_PASSWORD: admin123
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --query 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./clickhouse/users.xml:/etc/clickhouse-server/users.d/users.xml:ro
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml:ro
    networks:
      - lab-network

  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: bigdataspark-jupyter
    user: root
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      GRANT_SUDO: "yes"
      NB_UID: 1000
      NB_GID: 100
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    volumes:
      - ./:/home/jovyan/work
      - ./jars:/home/jovyan/jars:ro
    ports:
      - "8888:8888"
    networks:
      - lab-network
    command: >
      bash -c "
        pip install --quiet psycopg2-binary &&
        start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
      "

volumes:
  postgres-data:
  clickhouse-data:

networks:
  lab-network:
    driver: bridge
